app:
  datasource:
    jdbc-url: jdbc:h2:file:~/h2_db;AUTO_SERVER=TRUE
#    jdbc-url: jdbc:h2:file:./default;AUTO_SERVER=TRUE
    username: user
    password: password
    pool-size: 5
    driver-class-name: org.h2.Driver

